//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerWebApi.Models.enty
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispositivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dispositivo()
        {
            this.dispositivo_configuracion = new HashSet<dispositivo_configuracion>();
            this.dispositivo_historico = new HashSet<dispositivo_historico>();
            this.dispositivo_zonasegura = new HashSet<dispositivo_zonasegura>();
            this.dispositivo_zonawifi = new HashSet<dispositivo_zonawifi>();
            this.gps = new HashSet<gps>();
        }
    
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string placa { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dispositivo_configuracion> dispositivo_configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dispositivo_historico> dispositivo_historico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dispositivo_zonasegura> dispositivo_zonasegura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dispositivo_zonawifi> dispositivo_zonawifi { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gps> gps { get; set; }
    }
}
