// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SVAIOT_Database
{
    public partial class DispositivoZonasegura
    {
        public int Id { get; set; }
        public int IdDispositivo { get; set; }
        public string Nombre { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public double Presicion { get; set; }
        public int Rango { get; set; }
        public bool Estado { get; set; }

        public virtual Dispositivo IdDispositivoNavigation { get; set; }
    }
}