// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SVAIOT_Database
{
    public partial class Dispositivo
    {
        public Dispositivo()
        {
            DispositivoConfiguracion = new HashSet<DispositivoConfiguracion>();
            DispositivoHistorico = new HashSet<DispositivoHistorico>();
            DispositivoZonasegura = new HashSet<DispositivoZonasegura>();
            DispositivoZonawifi = new HashSet<DispositivoZonawifi>();
            Gps = new HashSet<Gps>();
        }

        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Placa { get; set; }
        public string Descripcion { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<DispositivoConfiguracion> DispositivoConfiguracion { get; set; }
        public virtual ICollection<DispositivoHistorico> DispositivoHistorico { get; set; }
        public virtual ICollection<DispositivoZonasegura> DispositivoZonasegura { get; set; }
        public virtual ICollection<DispositivoZonawifi> DispositivoZonawifi { get; set; }
        public virtual ICollection<Gps> Gps { get; set; }
    }
}