// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SVAIOT_Database
{
    public partial class DispositivoZonawifi
    {
        public int Id { get; set; }
        public int IdDispositivo { get; set; }
        public string Nombre { get; set; }
        public bool EsFisico { get; set; }
        public string Serial { get; set; }
        public bool Estado { get; set; }

        public virtual Dispositivo IdDispositivoNavigation { get; set; }
    }
}