// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SVAIOT_Database
{
    public partial class Usuario
    {
        public Usuario()
        {
            Dispositivo = new HashSet<Dispositivo>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Documento { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public byte[] Genera { get; set; }
        public bool Activo { get; set; }

        public virtual UsuarioCredenciales UsuarioCredenciales { get; set; }
        public virtual ICollection<Dispositivo> Dispositivo { get; set; }
    }
}