// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SVAIOT_Database
{
    public partial class UsuarioCredenciales
    {
        public int IdUsuario { get; set; }
        public string CrypUsername { get; set; }
        public string CrypPassword { get; set; }
        public string SerialDispositivo { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}